swipe:
  4:
    right:
      command: 'xdotool key alt+Right' # History forward
    left:
      command: 'xdotool key alt+Left' # History back
    up:
      command: 'xdotool key ctrl+t' # Open new tab
      keypress:
        LEFTSHIFT:
          command: 'xdotool key --clearmodifiers ctrl+shift+t' # Open last closed tab
    down:
      command: 'xdotool key ctrl+w' # Close tab
  3:
    left:
      workspace: 'next' # Switch to next workspace
      keypress:
        LEFTSHIFT:
          command: 'xdotool key super+ctrl+shift+Right' # Move window to next workspace
        LEFTMETA:
          command: 'xdotool key Left' # Move window to left side
    right:
      workspace: 'prev' # Switch to previous workspace
      keypress:
        LEFTSHIFT:
          command: 'xdotool key super+ctrl+Left' # Move window to previous workspace
        LEFTMETA:
          command: 'xdotool key Right'  # Move window to right side
    up:
      command: 'xdotool key super+w' # Workspace overview
      keypress:
        LEFTMETA:
          command: 'xdotool key Page_Up' # Maximize/unmaximize window
    down:
      command: 'xdotool key Control_L+F12' #minimise all windows
      keypress:
        LEFTALT:
          command: 'xdotool key F4'

pinch:
  2:
    in:
      command: 'xdotool keydown ctrl click 4 keyup ctrl' # Zoom in
    out:
      command: 'xdotool keydown ctrl click 5 keyup ctrl' # Zoom out

threshold:
  pinch: 0.2

interval:
  pinch: 0.4

plugin:
  inputs:
    libinput_command_input: # options for lib/plugin/inputs/libinput_command_input
      enable-tap: true # click to tap
      enable-dwt: true # disable tap while typing
      show-keycodes: true # https://github.com/iberianpig/fusuma-plugin-keypress#add-show-keycode-option
