#!/bin/sh

case $1 in
    pre) /usr/local/bin/power_save.sh false ;;
    post)
	if cat /sys/class/power_supply/ACAD/online | grep 0 > /dev/null 2>&1
	then
    		/usr/local/bin/power_save.sh true
	else
    		/usr/local/bin/power_save.sh false
	fi
    ;;
esac
exit 0
